spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: clientId
            clientSecret: clientSecret
            scope:
              - email
              - profile
  application:
    name: hotelmanager