spring:
  datasource:
    url: jdbc:mysql://localhost:3306/QuanLyKhachSan_dev
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true