app:
  config:
    host: host.docker.internal
    keycloak:
      url: http://${app.config.host}:8080/auth
      realm: qlks
      client-id: hotel-user-management
      client-secret: NlGOd0I0GWrTJrtwvQbH0FatJfuN5LPf

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka

spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/QuanLyKhachSan_dev?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        format_sql: true
